# Generated by Django 4.2.8 on 2024-03-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
